# Generated by Django 6.0.1 on 2026-02-10 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0001_initial'),
        ('contests', '0001_initial'),
        ('problems', '0002_problem_contest_problem_memory_limit_and_more'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('running', 'Ishlayapti'), ('accepted', 'Qabul qilindi'), ('wrong_answer', "Noto'g'ri javob"), ('time_limit', 'Vaqt chegarasi'), ('runtime_error', 'Ishlash xatosi'), ('compile_error', 'Kompilyatsiya xatosi')], default='pending', max_length=20)),
                ('execution_time', models.IntegerField(default=0, help_text='ms')),
                ('memory_used', models.FloatField(default=0, help_text='MB')),
                ('test_results', models.JSONField(default=list, help_text='[{"test_case": 1, "status": "passed", "time": 100}]')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contest')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='baseuser.userprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='Submissions',
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'contest'], name='submissions_user_id_3cb229_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'submitted_at'], name='submissions_status_37dcdc_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contest', 'status'], name='submissions_contest_860f39_idx'),
        ),
    ]
