# Generated by Django 6.0.1 on 2026-02-10 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0002_baseuser'),
        ('submissions', '0002_submission_delete_submissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='baseuser.baseuser'),
        ),
    ]
