# Generated by Django 6.0.2 on 2026-02-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0004_baseuser_iat'),
        ('contests', '0002_alter_contest_participants_and_more'),
        ('problems', '0002_problem_contest_problem_memory_limit_and_more'),
        ('submissions', '0003_alter_submission_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem', 'status'], name='submissions_user_id_108b50_idx'),
        ),
    ]
