# Generated by Django 6.0.2 on 2026-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_submissions_user_id_108b50_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='memory_used',
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
