# Generated by Django 6.0.2 on 2026-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='modul',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
    ]
