# Generated by Django 6.0.2 on 2026-03-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '✨ Mavzu', 'verbose_name_plural': '✨ Mavzular'},
        ),
        migrations.AlterUniqueTogether(
            name='modul',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='modul',
            name='slug',
        ),
    ]
