# Generated by Django 6.0.2 on 2026-03-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_options_alter_modul_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '📝 Dars', 'verbose_name_plural': '📝 Darslar'},
        ),
        migrations.AlterModelOptions(
            name='modul',
            options={'verbose_name': '📚 Kurs', 'verbose_name_plural': '📚 Kurslar'},
        ),
    ]
