# Generated by Django 6.0.2 on 2026-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_options_alter_modul_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Agar chegirma bo'lsa, yakuniy narxni kiriting", max_digits=10, null=True, verbose_name='Chegirmadagi narx'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Kursning asosiy narxi (masalan: 500000.00)', max_digits=10, verbose_name='Kurs narxi'),
        ),
    ]
