# Generated by Django 6.0.1 on 2026-02-01 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Dasturlash tili',
                'verbose_name_plural': 'Dasturlash tillari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem_type', models.CharField(choices=[('darslik', 'darslik'), ('test', 'test'), ('probelm', 'probelm')], default=False, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('constraints', models.TextField(default='\n        <ul>\n            <li><code>2 ≤ nums.length ≤ 10<sup>4</sup></code></li>\n        </ul>\n        ', help_text='HTML formatida cheklovlar')),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 'Oson'), (2, 'O‘rtacha'), (3, 'Qiyin')], default=1)),
                ('points', models.PositiveIntegerField(default=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.category')),
                ('language', models.ManyToManyField(blank=True, related_name='problems', to='problems.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.tags')),
            ],
            options={
                'verbose_name': 'Masala',
                'verbose_name_plural': 'Masalalar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_txt', models.TextField(help_text="Kirish ma'lumotlari, masalan: '[2,7,11,15]\\n9'")),
                ('output_txt', models.TextField(help_text="Chiqish ma'lumotlari, masalan: '[0,1]'")),
                ('explanation', models.TextField(help_text='Tushuntirish matni')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Misol',
                'verbose_name_plural': 'Misollar',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_txt', models.CharField(help_text='Test Input', max_length=250)),
                ('output_txt', models.CharField(help_text='Chiqish Output', max_length=250)),
                ('is_correct', models.BooleanField(default=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_problem', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Test case',
                'verbose_name_plural': 'Test caselar',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('function', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Funksiya shabloni',
                'verbose_name_plural': 'Funksiya shablonlari',
                'unique_together': {('problem', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ExecutionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top_code', models.TextField(blank=True, null=True)),
                ('bottom_code', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_language', to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_problem', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Ishga tushirish testi',
                'verbose_name_plural': 'Ishga tushirish testlari',
                'unique_together': {('problem', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_active', 'difficulty'], name='problems_pr_is_acti_bcc8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='problems_pr_slug_19f4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['problem'], name='problems_te_problem_71dd6a_idx'),
        ),
    ]
