# Generated by Django 6.0.2 on 2026-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examples',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='examples',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='executiontestcase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='executiontestcase',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='function',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='function',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(blank=True, default=256, help_text='Megabaytlarda', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(blank=True, default=2000, help_text='Millisekundlarda', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
