# Generated by Django 6.0.2 on 2026-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_remove_examples_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
    ]
