# Generated by Django 6.0.2 on 2026-03-20 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_options_alter_modul_unique_together_and_more'),
        ('problems', '0006_problem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='courses.lesson'),
        ),
    ]
