# Generated by Django 6.0.2 on 2026-03-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '📁 Kategoriya', 'verbose_name_plural': '📂 Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'verbose_name': '🎯 Topshiriq', 'verbose_name_plural': '⚔️ Topshiriqlar'},
        ),
        migrations.AlterModelOptions(
            name='examples',
            options={'verbose_name': '📝 Misol', 'verbose_name_plural': '📋 Misollar'},
        ),
        migrations.AlterModelOptions(
            name='executiontestcase',
            options={'verbose_name': '🚀 Kod testi', 'verbose_name_plural': '⚙️ Kod testlari'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': '🧩 Funksiya shabloni', 'verbose_name_plural': '🛠️ Funksiya shablonlari'},
        ),
        migrations.AlterModelOptions(
            name='hint',
            options={'verbose_name': '🔑 Yordam', 'verbose_name_plural': '💡 Yordamlar'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': '💻 Dasturlash tili', 'verbose_name_plural': '⚙️ Dasturlash tillari'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['name'], 'verbose_name': '🏷️ Teg', 'verbose_name_plural': '🔖 Teglar'},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': '🧪 Test case', 'verbose_name_plural': '✅ Test caselar'},
        ),
    ]
