# Generated by Django 6.0.2 on 2026-03-22 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_category_options_alter_challenge_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='points',
        ),
        migrations.AddField(
            model_name='problem',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text="Ushbu masalani yechgan foydalanuvchiga beriladigan ball (XP). Agar bo'sh qoldirilsa, qiyinchilikka qarab avtomat belgilanadi: Oson: 100, O'rtacha: 250, Qiyin: 500.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Tajriba ochkosi (XP)'),
        ),
    ]
