# Generated by Django 6.0.1 on 2026-02-10 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0002_baseuser'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(related_name='registered_contests', through='contests.ContestRegistration', to='baseuser.baseuser'),
        ),
        migrations.AlterField(
            model_name='contestregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_registrations', to='baseuser.baseuser'),
        ),
    ]
