# Generated by Django 6.0.2 on 2026-03-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_alter_contest_participants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-start_time'], 'verbose_name': '🏆 Musobaqa', 'verbose_name_plural': '🏁 Musobaqalar'},
        ),
        migrations.AlterModelOptions(
            name='contestregistration',
            options={'ordering': ['rank', '-total_score'], 'verbose_name': "🪪 Ro'yxatdan o'tish", 'verbose_name_plural': "👥 Ro'yxatdan o'tganlar"},
        ),
    ]
