# Generated by Django 6.0.2 on 2026-03-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '🎬 Video', 'verbose_name_plural': '🎥 Videolar'},
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='video_video_slug_89c582_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='video_video_id_761ed0_idx',
        ),
    ]
