# Generated by Django 6.0.2 on 2026-03-20 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0004_baseuser_iat'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Shablon nomi')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='cert_templates/', verbose_name='Fon rasmi')),
                ('html_template', models.TextField(help_text="Mavjud o'zgaruvchilar: {{ full_name }}, {{ test_title }}, {{ score }}, {{ percentage }}, {{ date }}, {{ certificate_id }}, {{ qr_code }}", verbose_name='HTML shablon')),
                ('min_percentage', models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='Sertifikat uchun minimal foiz')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='courses.course', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Sertifikat shabloni',
                'verbose_name_plural': 'Sertifikat shablonlari',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Rasm (ixtiyoriy)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizs.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Davomiyligi (daqiqa)')),
                ('question_count', models.PositiveIntegerField(default=20, verbose_name='Savollar soni')),
                ('max_attempts', models.PositiveIntegerField(default=0, verbose_name='Maksimal urinishlar soni (0 = cheksiz)')),
                ('access_code', models.CharField(blank=True, max_length=50, null=True, verbose_name="Kirish kodi (bo'sh = ochiq)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizs.test', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('expired', "Muddati o'tgan")], default='in_progress', max_length=20, verbose_name='Holat')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('score', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Foiz')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Sertifikat ID')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Sertifikat (PDF)')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quizs.test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test sessiyasi',
                'verbose_name_plural': 'Test sessiyalari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Belgilangan (flag)')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizs.choice', verbose_name='Tanlangan javob')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizs.question', verbose_name='Savol')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizs.testsession', verbose_name='Sessiya')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi javobi',
                'verbose_name_plural': 'Foydalanuvchi javoblari',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
