# Generated by Django 6.0.2 on 2026-03-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'verbose_name': '📜 Sertifikat shabloni', 'verbose_name_plural': '🎨 Sertifikat shablonlari'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['question', 'order'], 'verbose_name': '🔘 Javob varianti', 'verbose_name_plural': '✅ Javob variantlari'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['test', 'order'], 'verbose_name': '❓ Savol', 'verbose_name_plural': '❔ Savollar'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at'], 'verbose_name': '📝 Test', 'verbose_name_plural': '📑 Testlar'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'ordering': ['-started_at'], 'verbose_name': '⏱️ Test sessiyasi', 'verbose_name_plural': '📊 Test sessiyalari'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': '👤 Foydalanuvchi javobi', 'verbose_name_plural': '📥 Foydalanuvchi javoblari'},
        ),
    ]
