# Generated by Django 6.0.2 on 2026-03-22 12:40

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0005_alter_baseuser_options'),
        ('courses', '0006_course_discount_price_course_price'),
        ('quizs', '0002_alter_certificatetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsession',
            options={'verbose_name': '⏱️ Test sessiyasi', 'verbose_name_plural': '📊 Test sessiyalari'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={},
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='html_template',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='is_flagged',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text="Bo'sh qolsa: Oson-10, O'rtacha-25, Qiyin-50 ball beriladi.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='XP'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='total_xp_earned',
            field=models.PositiveIntegerField(default=0, verbose_name="To'plangan XP"),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(default=datetime.datetime(2026, 3, 22, 12, 40, 21, 434707, tzinfo=datetime.timezone.utc), upload_to='cert_templates/', verbose_name='Fon rasmi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='min_percentage',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='Minimal foiz (%)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizs.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='certificate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar"),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('expired', "Muddati o'tgan")], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quizs.test'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='baseuser.baseuser'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizs.choice'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizs.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizs.testsession'),
        ),
    ]
