# Generated by Django 6.0.2 on 2026-03-22 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0003_alter_testsession_options_alter_useranswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['deadline'], 'verbose_name': '📝 Test', 'verbose_name_plural': '📑 Testlar'},
        ),
        migrations.AddField(
            model_name='test',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 14, 26, 11, 904997, tzinfo=datetime.timezone.utc), help_text="Ushbu vaqtdan keyin testni boshlab bo'lmaydi", verbose_name='Testning tugash muddati'),
            preserve_default=False,
        ),
    ]
