# Generated by Django 6.0.2 on 2026-03-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0004_alter_test_options_test_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Foydalnovchi tugatgan vaqti'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
    ]
