# Generated by Django 6.0.1 on 2026-02-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0002_baseuser'),
        ('contests', '0002_alter_contest_participants_and_more'),
        ('submissions', '0003_alter_submission_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
