# Generated by Django 6.0.1 on 2026-02-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='iat',
            field=models.IntegerField(blank=True, help_text='JWT tokenning issued at timestampi', null=True, verbose_name='Token issued at'),
        ),
    ]
