# Generated by Django 6.0.2 on 2026-03-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0004_baseuser_iat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'ordering': ['-created_at'], 'verbose_name': '👤 Foydalanuvchi', 'verbose_name_plural': '👥 Foydalanuvchilar'},
        ),
    ]
